# Generated by Django 3.1.7 on 2021-05-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brand_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.IntegerField()),
                ('item_name', models.TextField()),
                ('item_img', models.ImageField(upload_to='pics')),
                ('item_price', models.IntegerField()),
                ('item_size', models.IntegerField()),
            ],
        ),
    ]
