# Generated by Django 3.1.7 on 2021-05-05 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('accounts', '0003_auto_20210504_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user_login')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.brand_new')),
            ],
        ),
    ]
